adding all primitive to the supported types
gotnospirit/messageformat pull request #2
Opened 2019-07-17 15:58 UTC by jpnjfk

The toString() in utils.go supports just nil, string, int and float64.
When a variable in the given map is explecitly defined with a type such as int64 and 
int32, the toString returns the error as "toString: Unsupported type: int64".
Here is an example code.

var v int64
data := map[string]interface{}{
    "value": v,
}
result, err := toString(data, "value")

So, all of the primitive types should appear in the switch-case block in the toString().
In addition, I'd like the function to support time.Duration.

2019-07-17 22:01 UTC, gotnospirit requested changes
Hi!
I'm pretty open to add more support for builtin types to toString().
Before I merge it, please consider my comments.
Thank you for your time :)

2019-07-17 22:01 UTC, gotnospirit commented on utils.go
> +// It will returns an error if the value's type is not <premitive or time.Duration>.
We're implementing here a subset of numeric types so we can't pretend we did it for _all_ primitive types; therefore I would rephrase it as "<nil/string/numeric/time.Duration>".
Plus, to fully implement all the numeric types, we should add/extend cases for the missing ones: uintptr, complex64, complex128, byte & rune.

2019-07-17 22:01 UTC, gotnospirit commented on utils.go
> +			return v.(time.Duration).String(), nil
just on the form, could you rewrite it to follow this order:
- int, int8, int16, int32, int64
- uint, uint8, uint16, uint32, uint64
- float32, float64
- time.Duration

it just seems more logic to me, ty

2019-07-17 22:01 UTC, gotnospirit commented on utils_test.go
> +func TestToStringAdditionalTypes(t *testing.T) {
I think we should add specific tests for explicit numeric types and time duration. Something like TestToStringNumericTypes & TestToStringTimeDuration

2019-07-17 22:01 UTC, gotnospirit commented on utils_test.go
> +		"byteMax"   : byteMax,
for the sake of brevity we could just write `"byteMax": byte(255)` and then remove the associated var declaration & assignation. we could do the same for the other variables and save 21 lines :)

2019-07-17 22:01 UTC, gotnospirit commented on utils_test.go
> +	}
we should add keys for explicitly declared int/uint/float64

2019-07-17 22:01 UTC, gotnospirit commented on utils_test.go
> +}
some keys are not tested :(

on the form, it seems more logic to me to see the keys and their tests in the same order, ty

2019-07-17 22:03 UTC, gotnospirit commented
and "go fmt" please ;)

2019-07-18 03:42 UTC, jpnjfk commented
Thank you for quickly reviewing my changes and sending your comments.
I made the changes based on your suggestions.
The 'byte' is an alias of 'uint8' and the 'rune' is an alias of 'int32' so that I didn't add the case clause for them to the switch-case block in toString().
But I added them in the tests.

2019-07-18 19:04 UTC, gotnospirit requested changes
Thank you for the changes you added.
2 last comments and I would appreciate that you squash the commits you have done before merging.

2019-07-18 19:04 UTC, gotnospirit commented on utils.go
> +			return strconv.FormatFloat(float64(v.(float32)), 'f', -1, 32), nil
Could you reorder float32 then float64 please?

2019-07-18 19:04 UTC, gotnospirit commented on utils_test.go
> +		"float64":    float32(3.14e-10),
I think it should be `float64(3.14e-10)`

2019-07-18 19:48 UTC, jpnjfk commented
Thank you for reviewing my changes again. :)
I updated the points you suggested.

2019-07-18 19:50 UTC, jpnjfk reviewed
Thank you for reviewing my changes again. :)
I updated the points you suggested.

2019-07-18 19:50 UTC, jpnjfk commented on utils.go
> +			return v.(time.Duration).String(), nil
Done.

2019-07-18 19:50 UTC, jpnjfk commented on utils_test.go
> +	}
Done.

2019-07-18 19:50 UTC, jpnjfk commented on utils_test.go
> +}
Done.

2019-07-18 19:50 UTC, jpnjfk commented on utils.go
> +// It will returns an error if the value's type is not <premitive or time.Duration>.
Done.

2019-07-18 19:50 UTC, jpnjfk commented on utils_test.go
> +func TestToStringAdditionalTypes(t *testing.T) {
Done.

2019-07-18 19:50 UTC, jpnjfk commented on utils_test.go
> +		"byteMax"   : byteMax,
done.

2019-07-18 19:50 UTC, jpnjfk commented on utils.go
> +// It will returns an error if the value's type is not <premitive or time.Duration>.
I didn't add 'rune' and 'byte' to the switch-case block in toPrint() because it's aliases of uint8, int32 respectively.
I did add them in the tests.

2019-07-18 19:50 UTC, jpnjfk commented on utils.go
> +			return strconv.FormatFloat(float64(v.(float32)), 'f', -1, 32), nil
done.

2019-07-18 19:50 UTC, jpnjfk commented on utils_test.go
> +		"float64":    float32(3.14e-10),
done.

2019-07-19 00:19 UTC, jpnjfk commented
Also, I squashed my commits to one commit.

2019-07-19 17:40 UTC, merged

2019-07-19 17:44 UTC, gotnospirit commented
Thank you!

2019-07-19 17:56 UTC, jpnjfk commented
Great!!!
Thank you for your help. :)